### ISSUE TITLE
Dev content review 1

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/draft-guide-okd-crc#2]
- [x] does CRC contain OKD? What are their relationship? If no relationship or they are independent, suggest not include okd as the guide project id  and repo.
- [x] "Explore how to use CodeReady Containers to deploy microservices to Red Hat OpenShift." does not sound right.
- **"What you’ll learn"**
  - [x] better not copy the following statements, although RedHat is part of IBM
    - "Red Hat CodeReady Containers is the quickest way .... It is designed ..."
  - [x] suggest move the "Red Hat CodeReady Containers ..." paragraph to replace the "OpenShift is a Kubernetes-based platform..." paragraph
- **Additional prerequisites**
  - [x] is "OpenShift account" still need for CRC?
- **Deploying microservices to OpenShift**
  - **Building and containerizing the microservices**
    - [x] replace `openliberty/open-liberty:kernel-java8-openj9-ubi` to `openliberty/open-liberty:full-java8-openj9-ubi`
- [ ] Need to make sure CRC works on Win and Linux. It affects the guide content.

**Comment by griffinhadfield** [comment]
> does CRC contain OKD? What are their relationship? If no relationship or they are independent, suggest not include okd as the guide project id and repo.

OKD isn't part of OpenShift, that name was made earlier and is just a temporary name for now. I have changed it to "crc-openshift" now 

> is "OpenShift account" still need for CRC?

A Red Hat account is needed to install CRC however this is linked in the installation instructions anyway. I will take the account section out

> Need to make sure CRC works on Win and Linux. It affects the guide content.

I think Austin or Tien have a personal Windows computer they could test it on. Regarding testing it on Linux, I am not sure how to go about doing that as it is not recommended to use a VM.

**Comment by griffinhadfield** [comment]
Updated guide can be seen here: http://lgdev1.fyre.ibm.com:4020/guides/crc-openshift
