### ISSUE TITLE
Dev content review 2

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/draft-guide-okd-crc#3]
- **Starting CodeReady Containers**
  - **Logging in to the cluster**
    - [x] Need users to run the `set` or `export`? Better make it clear
    - [x] suggest hard code the project-name instead users to replace, e.g. my-project, system-inventory, guide-crc-openshift or better name
      - need to update the clean up step for  project-name

**Comment by griffinhadfield** [comment]
>  Need users to run the set or export? Better make it clear

They just need to run `eval $(crc oc-env)`, the snippet that includes the `export` line is just an example of the output. 

I changed the following instruction to hopefully make that clear 
> Run the appropriate command *specified in the output* to configure your environment:
(Italics aren't present in the guide)
