### ISSUE TITLE
Peer Review - Mac

### ISSUE THREAD

**Issue by AustinSeto** [OpenLiberty/draft-guide-okd-crc#4]
Functionality
---
- [ ] Check that the guide has working instructions and sample code
- [x] If any URL visits, try them on different browsers: Firefox, Chrome, Safari
- [x] If any URL visits, try `curl` command where applicable 

Formatting & Presentation
---

`README.adoc` checks:
- [x] Ensure that command substitutions use the `$(cmd)` format and not ``` `cmd` ```
- [ ] Ensure that the console output of the integrated tests do not include the `[INFO]` tab
- [ ] Check the quality and presentation of guide according to [Structure and Style Guideline](https://github.com/OpenLiberty/draft-guides-template/wiki/Guidelines-for-Structure-and-Styles)
- [ ] Check that the pom.xml, server.xml, etc files are clean
    - [x] Remove any dependencies and features that are not required
    - [x] Ensure that the parent pom.xml files do not contain any dependencies, and all dependencies are specified in the children pom.xml files
- [x] Examples with the right outcomes are provided
- [x] Examples with the wrong outcomes, if any, are provided

`pom.xml` checks (if files are present):
- [x] Check that the file follows the template found here: https://github.com/OpenLiberty/draft-guides-template/blob/draft/finish/pom.xml
- [x] Check that the following dependencies are included in all of the `pom.xml` files:
```
<!-- Provided dependencies -->
<dependency>
  <groupId>jakarta.platform</groupId>
  <artifactId>jakarta.jakartaee-api</artifactId>
  <version>8.0.0</version>
  <scope>provided</scope>
</dependency>

<dependency>
  <groupId>org.eclipse.microprofile</groupId
  <artifactId>microprofile</artifactId>
  <version>3.3</version>
  <type>pom</type>
  <scope>provided</scope>
</dependency>
```
- [x]  Check that the versions of plugins are directly provided and not fed in by a file property.
  - Not formatted like so:
```
    <properties>
        <!-- Plugins -->
        <version.liberty-maven-plugin>3.2</version.liberty-maven-plugin>
    </properties>

    <!-- Liberty plugin -->
    <plugin>
        <groupId>io.openliberty.tools</groupId>
        <artifactId>liberty-maven-plugin</artifactId>
        <version>${version.liberty-maven-plugin}</version>
    </plugin>
```
  - Should be formatted like so:
```
    <!-- Liberty plugin -->
    <plugin>
        <groupId>io.openliberty.tools</groupId>
        <artifactId>liberty-maven-plugin</artifactId>
        <version>3.3.3</version>
    </plugin>
```
- [ ] Check that there are 4 spaces per indent for proper formatting
- [ ] Ensure that the guide is using the latest version of the `liberty-maven-plugin` or `liberty-gradle-plugin` where applicable

Overall checks:
- [x] Check the consistency of guide with the template and other guides
- [ ] Check the quality of code according to the best coding practices
- [ ] Check that all licensing statements are properly stated in all files, with the correct year (Should be present in all Java files + the `index.html`)
- [x] Check that the directories are properly structured
- [ ] Check that some of these `page-tags` are used in a guide: `MicroProfile, Maven, Docker, Kubernetes, Gradle, Java EE, Security, Cloud`. Only these tags are visible on the website. Latest list [here](https://github.com/OpenLiberty/openliberty.io/blob/master/src/main/content/_includes/visible-tags.liquid). 
- [x] Check the `attribution` statement is accurate for the guide
- [ ] Verify the GitHub Actions scripts, if any, are accurate and consistent with other guides

---

- [ ] Additional tests where applicable: 
    - [ ] Define test coverage and review with team (including guide contributor, if available)
    - [ ] Define detail test cases 
    - [ ] Consider corner cases targeting the specific guide
    - [ ] Consider corner cases UI tests
    - [ ] Consider testing URL on all browsers, ie, FF, Chrome, Safari
    - [ ] Consider testing the `curl` command for URL visits
    - [ ] Make sure the index.html information is correct by visiting the root, e.g. `http://localhost:9080`
- [ ] Consider building with both Maven and Gradle build tools 
- [x] Testing with different IDEs, ie, Atom, Eclipse (Optional: VS.code, IntelliJ, Microclimate)
- [x] Run Acrolinx Checker on draft (above 70 score approximately)
- [ ] Consider SEO title and description for the guides 
- [ ] Ensure automated tests with GitHub Actions are enabled
- [x] Run `diff -r start/ finish/` and there's no differences
- [ ] Ensure that the automation tests are able to run when PR is created
- [ ] Check the appearance of the guide on test site for the following items: 
    - [x] Table of contents 
    - [x] Headings
    - [x] Paragraphs
    - [ ] code snippets
    - [ ] outputs
    - [x] links
    - [x] hotspots 
- [ ] Test the guide end-to-end with working instruction and sample code
- [ ] Perform all the defined test cases

**Comment by AustinSeto** [comment]
Acrolinx: https://ibmid.acrolinx.cloud/api/v1/checking/scorecards/add25d19-0ff5-4459-b94b-4f58fcf6c7cc

# What You'll Learn

- [x] Capitalize CodeReady Containers in first paragraph
- [x] Update documentation link to latest version: https://access.redhat.com/documentation/en-us/red_hat_codeready_containers/1.23/html/getting_started_guide/index

# Additional Prerequisites

- [x] Update Docker link to https://docs.docker.com/get-docker/
- [x] Update link to official documentation to the latest version of the documentation listed here: https://access.redhat.com/documentation/en-us/red_hat_codeready_containers/1.23/html/getting_started_guide/installation_gsg

# Starting CodeReady Containers

- [ ] Command to log in should just be `eval $(crc oc-env)`, I don't think there is a need to ask the user to run `crc oc-env` by itself
- [ ] I think it can just say "Run `crc oc-env` to set up your environment" to simplify the "logging in" section
- [x] `oc login` command failed if I didn't include the URL `https://api.crc.testing:6443`

# Deploying microservices to OpenShift

- [x] I don't think explaining the `-t` flag in the `docker build` command is necessary, as that should be prerequisite knowledge, already covered in previous guides like `guide-containerize` which is linked in a previous section
- [ ] Instead of asking the user to look for the given key-value pair, then describing it again, might be better to just describe it once. For example, "Add the following key-value pair if it does not already exist in the JSON object."
- [x] My registry address is only displayed after running `oc registry info`, it is not displayed after running `echo $(oc whoami -t) | docker login -u developer --password-stdin $(oc registry info)`
- [ ] Got the following deprecation warning when running `oc apply -f kubernetes.yaml`
```
W0309 11:57:17.975040   77689 shim_kubectl.go:55] Using non-groupfied API resources is deprecated and will be removed in a future release, update apiVersion to "route.openshift.io/v1" for your resource
W0309 11:57:17.975501   77689 shim_kubectl.go:55] Using non-groupfied API resources is deprecated and will be removed in a future release, update apiVersion to "route.openshift.io/v1" for your resource
```
- [x] It is stated that the `kubernetes.yaml` file is provided for the user, but the user is instructed to create the file. Should remove the statement that the `kubernetes.yaml` file is provided. 
- [x] Adjust language to be more direct and active 
  - [x] "First, you must authenticate your Docker client to your OCR. Start by running the login command:" -> "Run the login command to authenticate your Docker client to your OCR."
  - [x] "In order to use the OpenShift registry with Docker, you must add the registry domain to your Docker Engine’s list of insecure registries." -> "Add the OpenShift registry domain to your Docker Engine's list of insecure registries to use it."


# Making requests to the microservice

- Had the following hostnames from `oc get routes`
  - `system-route-my-project.apps-crc.testing` for system
  - `inventory-route-my-project.apps-crc.testing` for inventory
- [ ] At `http://inventory-route-my-project.apps-crc.testing/inventory/systems/system-route-my-project.apps-crc.testing` got an error in the JSON response:
  - `{ "error" : "Unknown hostname or the system service may not be running on system-route-my-project.apps-crc.testing" }`
- [x] Adjust language to be more direct and active
  - [x] "To access the services and the application, use a route." -> "Routes are used to access the services and the application."
  - [x] "To access your microservices, point your browser to the following URLs." -> "Access the following URLs in your web browser to access your microservices."

# Testing the microservices

- [x] "example" should be plural in "similar to the following example"

# Code

- [x] Remove `target` subdirectories in `finish` directory
- [x] Update `liberty-maven-plugin` to latest version `3.3.4`
- [x] Update license years to 2021
- [ ] The file `scripts/test.yaml` doesn't appear to be referenced by the automated tests

**Comment by griffinhadfield** [comment]
> Command to log in should just be eval $(crc oc-env), I don't think there is a need to ask the user to run crc oc-env by itself

I worked through this section with Gilbert and I believe this is how he liked it. It is also consistent with how the Minishift guides do it.

> At http://inventory-route-my-project.apps-crc.testing/inventory/systems/system-route-my-project.apps-crc.testing got an error in the JSON response:

I wasn't able to reproduce this error, so it might be resolvable by giving it some more time. I have gotten other errors that fixed themselves by just giving a bit longer to fully start up

**Comment by griffinhadfield** [comment]
Addressed issues in https://github.com/OpenLiberty/draft-guide-crc-openshift/pull/8

**Comment by AustinSeto** [comment]
Comments addressed by PR and after discussing on Slack, closing issue
